Main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from cinema import views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_page, name='main'),
    path('cinema/', include('cinema.urls')),
    path('login/', LoginView.as_view(template_name='cinema/pages/account/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('profile/<int:pk>', views.UserDetailView.as_view(), name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/urls.py
from django.urls import path, include
from cinema import views

urlpatterns = [
    path('list/', views.movies_list_page, name='movies_list'),
    path('add/', views.add_cinema_page, name='add_movie'),
    path('<int:pk>/details', views.MovieDetailView.as_view(), name='movie_detail'),
    path('<int:pk>/update', views.MovieUpdateView.as_view(), name='movie_update'),
    path('<int:pk>/delete', views.MovieDeleteView.as_view(), name='movie_delete'),
    path("sessions/<movie_id>/create", views.SessionCreateView.as_view(), name="session_create"),
    path('review/<int:pk>/delete', views.ReviewDeleteView.as_view(), name='review_delete'),
    path('review/<int:pk>/update', views.ReviewUpdateView.as_view(), name='review_update'),
]

cinema/models.py
from django.db import models
from django.forms import IntegerField
from django.contrib.auth.models import User


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=30)
    company = models.CharField(max_length=30)
    description = models.TextField(max_length=500)
    year_released = models.DateField()
    length = models.IntegerField(default=0)
    genre = models.CharField(max_length=30)
    thumbnail = models.ImageField(upload_to='thumbnails/', verbose_name='Movie Poster')

    def __str__(self):
        return self.name

class Session(models.Model):
     movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
     date = models.DateField()
     start_time = models.TimeField()
     end_time = models.TimeField()
     audience_number = models.IntegerField(default=1)
     is_active = models.BooleanField(default=True)

     def __str__(self):
         return f"Session {self.id} | {self.movie.name}: {self.start_time} - {self.end_time} | Audience: {self.audience_number}"

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.TextField()
    review_date = models.DateField(auto_now_add=True)

    class Meta:
        unique_together = ('movie', 'user')

cinema/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from cinema.models import Movie, Review


class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'company', 'description', 'year_released', 'length', 'genre', 'thumbnail']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['review']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

cinema/views.py
import django.shortcuts
from django.contrib.auth import logout, login
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from cinema.forms import MovieForm, ReviewForm, UserRegistrationForm
from cinema.models import Movie, Session, Review

from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, UpdateView, CreateView

from django.contrib.auth.models import User, Group
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Create your views here.
def main_page(req):
    return render(req, 'cinema/pages/index.html')


def add_cinema_page(req):
    if req.method == 'POST':
        form = MovieForm(req.POST, req.FILES)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)

    form = MovieForm()

    context = {
        'form': form,
    }

    return render(req, 'cinema/pages/movies/CRUD/add.html', context=context)


def movies_list_page(req):
    movies = Movie.objects.all()
    print(movies)

    context = {
        'movies': movies,
    }

    return render(req, 'cinema/pages/movies/movies.html', context=context)


class MovieDetailView(LoginRequiredMixin, DetailView):
    model = Movie
    template_name = 'cinema/pages/movies/CRUD/read.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = Review.objects.filter(movie=self.object).order_by('-review_date')
        context['form'] = ReviewForm() if self.request.user.is_authenticated else None
        user = self.request.user
        if user.is_authenticated:
            groups = user.groups.values_list('name', flat=True)
            if user.is_staff:
                context['role'] = 'Staff'
            elif 'CEO' in groups:
                context['role'] = 'CEO'
            elif 'Employee' in groups:
                context['role'] = 'Employee'
            else:
                context['role'] = 'User'
        else:
            context['role'] = None
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not request.user.is_authenticated:
            return redirect('login')
        form = ReviewForm(request.POST)
        if form.is_valid():
            existing_review = Review.objects.filter(movie=self.object, user=request.user).first()
            if existing_review:
                return redirect(reverse('movie_detail', kwargs={'pk': self.object.pk}))

            review = form.save(commit=False)
            review.movie = self.object
            review.user = request.user
            review.save()
            return redirect(reverse('movie_detail', kwargs={'pk': self.object.pk}))
        return self.get(request, *args, **kwargs)


class MovieUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Movie
    fields = '__all__'
    template_name = 'cinema/pages/movies/CRUD/update.html'
    context_object_name = 'movie'
    permission_required = 'cinema.change_movie'

    def get_success_url(self):
        return reverse('movie_detail', kwargs={'pk': self.object.pk})


class MovieDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Movie
    template_name = 'cinema/pages/movies/CRUD/delete.html'
    context_object_name = 'movie'
    success_url = reverse_lazy('movies_list')
    permission_required = 'cinema.delete_movie'


class SessionCreateView(CreateView):
    model = Session
    fields = ['date', 'start_time', 'end_time', 'audience_number', 'is_active']

    template_name = 'cinema/pages/sessions/CRUD/create.html'

    def dispatch(self, request, *args, **kwargs):
        self.movie = django.shortcuts.get_object_or_404(Movie, pk=kwargs['movie_id'])
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('movie_detail', kwargs={'pk': self.movie.id})

    def form_valid(self, form):
        form.instance.movie = self.movie
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['movie'] = self.movie
        return context


class UserDetailView(DetailView):
    model = User
    template_name = 'cinema/pages/account/CRUD/read.html'
    context_object_name = 'user'


def logout_view(req):
    if req.method == 'POST':
        logout(req)
        return redirect('main')
    return render(req, 'cinema/pages/account/logout.html')


class UserRegisterView(View):
    def get(self, request):
        form = UserRegistrationForm()
        context = {
            'form': form,
        }
        return render(request, 'cinema/pages/account/register.html', context=context)

    def post(self, request):
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            user = form.save()
            user_group = Group.objects.get(name='User')
            user.groups.add(user_group)

            login(request, user)
            return redirect('main')

        return render(request, "cinema/pages/account/register.html", {'form': form})


class ReviewDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Review
    template_name = 'cinema/pages/reviews/CRUD/delete.html'
    context_object_name = 'review'
    permission_required = 'cinema.delete_review'

    def get_success_url(self):
        return reverse('movie_detail', kwargs={'pk': self.object.movie.id})


class ReviewUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Review
    template_name = 'cinema/pages/reviews/CRUD/update.html'
    context_object_name = 'review'
    permission_required = 'cinema.change_review'
    fields = ['review']

    def get_success_url(self):
        return reverse('movie_detail', kwargs={'pk': self.object.movie.id})

cinema/templates/cinema/pages/movies/accordions.html
<div class="movie-additional">
	<div class="accordion" id="accordionFlushExample">
		<div class="accordion-item">
			<h2 class="accordion-header">
				<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
						data-bs-target="#flush-collapseOne" aria-expanded="false"
						aria-controls="flush-collapseOne">
					Description
				</button>
			</h2>
			<div id="flush-collapseOne" class="accordion-collapse collapse">
				<div class="accordion-body">
					{{ movie.description }}
				</div>
			</div>
		</div>
		<div class="accordion-item">
			<h2 class="accordion-header">
				<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
						data-bs-target="#flush-collapseTwo" aria-expanded="false"
						aria-controls="flush-collapseTwo">
					Sessions
				</button>
			</h2>
			<div id="flush-collapseTwo" class="accordion-collapse collapse">
				<div class="accordion-body">
					{% if movie.session_set.all %}
						{% for session in movie.session_set.all %}
							{% if session.is_active %}
								<button class="btn m-3">
									{{ session.date|date:"M d" }}, {{ session.start_time }} - {{ session.end_time }}
								</button>
							{% endif %}
						{% endfor %}
					{% else %}
						<p style="text-align: center;">There aren't any free sessions for the film!</p>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

cinema/templates/cinema/pages/movies/movies.html
{% extends 'cinema/template.html' %}

{% block title %} Movies {% endblock %}

{% block content %}
	<div class="container mt-3 d-flex flex-column align-items-center justify-content-center">
		<h1>Movies</h1>
		<div class="container d-flex flex-wrap">
			{% if movies %}
				{% for movie in movies %}
					<a href="{% url 'movie_detail' movie.id %}" class="movie mx-3">
						<div class="poster d-flex justify-content-center align-items-center">
							<img src="{{ movie.thumbnail.url }}" alt="movie">
						</div>
						<div class="movie-info">
							<h3>{{ movie.name }}</h3>
						</div>
					</a>
				{% endfor %}
			{% else %}
				<h2>There aren't any availables movies to watch!</h2>
			{% endif %}
		</div>
	</div>
{% endblock %}

cinema/templates/cinema/pages/movies/reviews.html
{% load static %}

<form method="post" enctype="multipart/form-data">
	<div class="d-flex flex-column form align-items-center justify-content-center review-form">
		{% csrf_token %}
		{% for field in form %}
			<div class="mb-3 d-flex flex-column custom-review-label">
				<label class="form-label-tag">{{ field.label_tag }}</label>
				{{ field }}
			</div>
		{% endfor %}
		<button type="submit" class="btn btn-success">Add Review</button>
	</div>
</form>
{% for review in movie.review_set.all %}
	<div class="user-review my-2">
		<a href="{% url 'profile' review.user.id %}"
		   class="user-review-info d-flex align-items-center justify-content-center m-2">
			<img src="{% static 'images/user_logo.png' %}" alt="user_logo.png">
			<div class="user-review-details">
				<h3 style="">{{ review.user.username }}</h3>
			</div>
		</a>
		<div class="user-review-text">
			<textarea cols="30" rows="10" disabled readonly> {{ review.review }}</textarea>
		</div>
		<div class="user-review-controls">
			<div class="user-review-review">
				<h4 style="text-align: start">Reviewed on {{ review.review_date }}</h4>
			</div>
			<div class="user-review-buttons">
				{% if review.user.id == user.id %}
					<a href="{% url 'review_update' review.id %}" class="btn btn-warning">Edit</a>
					<a href="{% url 'review_delete' review.id %}" class="btn btn-secondary">Delete</a>
				{% elif role == "CEO" or role == "Employee" or role == "Staff" %}
					{% if perms.cinema.change_review %}
						<a href="{% url 'review_update' review.id %}" class="btn btn-warning">Edit</a>
					{% endif %}

					{% if perms.cinema.delete_review %}
						<a href="{% url 'review_delete' review.id %}" class="btn btn-secondary">Delete</a>
					{% endif %}
				{% endif %}
			</div>
		</div>
	</div>
{% endfor %}